---
### CONFIG - Infernus101###
# show player's rank? 0 to disable, only pureperms support
rank: 1
# show player's money? 0 to disable, only economy by onebone support
money: 1
# show player's faction? 0 to disable, only FactionsPro by tethered support
faction: 1
# show player's first joined? 0 to disable
first-played: 1
# show player's last seen? 0 to disable
last-seen: 1
...
